version: '2'
services: 
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
    kafkaserver:
        image: spotify/kafka
        ports:
            - 2181:2181
            - 9092:9092