eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
  port: 8080
spring:
  application:
    name: licensingservice
  cloud:
    config:
      uri: http://localhost:8888/licensingservice
  profiles:
    active: default