eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
  port: 8082
spring:
  application:
    name: licensingservice
  cloud:
    stream:
      bindings:        
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: localhost  
    config:
      uri: http://localhost:8888/licensingservice
  profiles:
    active: default