eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
  port: 8080
spring:
  application:
    name: licensingservice
  cloud:
    stream:
      input:
        destination: orgChangeTopic
        content-type: application/json
        group: licensingGroup
      binder:
        zkNodes: localhost
        brokers: localhost  
    config:
      uri: http://localhost:8888/licensingservice
  profiles:
    active: default