eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: organizationservice
  cloud:
    config:
      uri: http://localhost:8888/organizationservice
  profiles:
    active: default
