server:
  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:////Users/qinritukou/Documents/GitHub/Spring-With-Docker/confsvr/src/main/resources/config/licensingservice,file:////Users/qinritukou/Documents/GitHub/Spring-With-Docker/confsvr/src/main/resources/config/organizationservice,file:////Users/qinritukou/Documents/GitHub/Spring-With-Docker/confsvr/src/main/resources/config/zuulsvr,file:////Users/qinritukou/Documents/GitHub/Spring-With-Docker/confsvr/src/main/resources/config/specialroutesservice
